# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arneva
email: arneva47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Krovinių pervežimas tarp Lietuvos ir Vakarų Europos, Techninė Pagalba kelyje Vilkaviškis, Autoservisas Vilkavišks
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arneva.lisk.lt" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
